export const RACAS = [
  'SRD (Vira-lata)',
  'Labrador Retriever',
  'Golden Retriever',
  'Poodle',
  'Bulldog Francês',
  'Bulldog Inglês',
  'Yorkshire Terrier',
  'Shih Tzu',
  'Pinscher',
  'Chihuahua',
  'Lhasa Apso',
  'Beagle',
  'Cocker Spaniel',
  'Border Collie',
  'Pastor Alemão',
  'Rottweiler',
  'Dachshund (Salsicha)',
  'Maltês',
  'Schnauzer',
  'Boxer',
  'Pug',
  'Basset Hound',
  'Akita',
  'Husky Siberiano',
  'Dálmata',
  'Pit Bull',
  'Fox Paulistinha',
  'Spitz Alemão (Lulu da Pomerânia)',
]
